use_modular_headers!
platform :ios, '10.0'

target 'XKToastExtension_Example' do
  pod 'XKToastExtension', :path => '../'

  target 'XKToastExtension_Tests' do
    inherit! :search_paths

    
  end
end
